const base = "/marketing/enterprise";

export const ENTERPRISE_IMG = {
  navLogo: `${base}/nav-logo.svg`,
  footerLogo: `${base}/footer-logo.svg`,
  footerHouse: `${base}/footer-house.svg`,
  heroPortrait: `${base}/hero-portrait.png`,
  heroMobile: "/marketing/hub/mobile-hub-image.png",
  heroMobile2x: "/marketing/hub/mobile-hub-image@2x.png",
  heroUnionBlob: `${base}/hero-union-blob.svg`,
  heroUnderline: `${base}/hero-underline.svg`,
  heroSparkline: `${base}/hero-sparkline.svg`,
  heroMonthlyBadge: `${base}/hero-monthly-badge.svg`,
  caseStudyAmazon: `${base}/case-study-amazon.svg`,
  benefitsDecor: `${base}/benefits-decor.svg`,
  benefitsUnderline: `${base}/benefits-underline.svg`,
  missionPhoto1: `${base}/mission-photo-1.png`,
  missionPhoto2: `${base}/mission-photo-2.png`,
  missionPhoto3: `${base}/mission-photo-3.png`,
  missionPhoto4: `${base}/mission-photo-4.png`,
  socialFacebook: `${base}/social-facebook.svg`,
  socialInstagram: `${base}/social-instagram.svg`,
  socialX: `${base}/social-x.svg`,
  socialLinkedin: `${base}/social-linkedin.svg`,
  socialYoutube: `${base}/social-youtube.svg`,
} as const;
